apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  name: ${APP}
  namespace: mytest
  labels:
    app: ${APP}
spec:
  rules:
    - host: ${APP}.${MY_DOMAIN}
      http:
        paths:
          - backend:
              serviceName: ${APP}
              servicePort: 8080
            path: /
  tls:
    - hosts:
        - ${APP}.${MY_DOMAIN}
      secretName: ingress-cert-${LETSENCRYPT_ENVIRONMENT}
